# Generated by Django 3.2.7 on 2021-09-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Список пользователей',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=150, verbose_name='Адрес')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Список недвижимости',
            },
        ),
    ]
