# Generated by Django 3.2.7 on 2021-09-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='api.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
